# Generated by Django 5.0.7 on 2024-09-07 16:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите ФИО", max_length=150, verbose_name="ФИО"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Инженер 1 категории", "Инженер 1 категории"),
                            ("Инженер 2 категории", "Инженер 2 категории"),
                            ("Инженер 3 категории", "Инженер 3 категории"),
                            ("Начальник отдела", "Начальник отдела"),
                        ],
                        help_text="выберите должность",
                        max_length=50,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="введите служебный email сотрудника",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="введите номер телефона",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Телефон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название задачи",
                        max_length=150,
                        verbose_name="Название задачи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="опишите задачу",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        help_text="введите срок выполнения",
                        verbose_name="Срок выполнения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Открыта", "Открыта"),
                            ("В исполении", "В исполении"),
                            ("Закрыта", "Закрыта"),
                        ],
                        default="Открыта",
                        help_text="выберите статус задачи",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        help_text="выберите исполнителя",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ttracker.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parental_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пример: Разработка схемы интерфейса передачи данных может быть связана с разработкой схемы вычислителя, как дочерняя задача",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ttracker.task",
                        verbose_name="Ссылка на родительскую задачу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
