# Generated by Django 5.0.7 on 2024-09-08 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ttracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="vacation_status",
            field=models.BooleanField(
                default=False,
                help_text="статус нахождения в отпуске",
                verbose_name="Статус отпуска",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Признак активности задачи"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_important",
            field=models.BooleanField(
                default=False, verbose_name="Признак важности задачи"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("category 1", "Инженер 1 категории"),
                    ("category 2", "Инженер 2 категории"),
                    ("category 3", "Инженер 3 категории"),
                    ("manager", "Начальник отдела"),
                ],
                default="category 3",
                help_text="выберите должность",
                max_length=50,
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Открыта"),
                    ("in_progress", "В исполении"),
                    ("done", "Закрыта"),
                ],
                default="open",
                help_text="выберите статус задачи",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
