# Generated by Django 5.0.7 on 2024-09-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ttracker", "0002_employee_vacation_status_task_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_important",
        ),
    ]
